name: Build and Deploy Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
      runs-on: diablo-client-runner

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Log in to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build and push client image
          run: |
            ls -a
            docker build -t ${{ secrets.DOCKER_USERNAME }}/diablo:${{ github.run_number }} -t ${{ secrets.DOCKER_USERNAME }}/diablo:latest
            docker push ${{ secrets.DOCKER_USERNAME }}/diablo --all-tags

        - name: Apply Kubernetes
          run: |
            kubectl create namespace diablo || true
            export RUN_ID=${{ github.run_number }}
            ls -a
            for file in ./*; do
                echo "Applying $file"
                cat $file | envsubst | /home/parker/.nix-profile/bin/kubectl apply -f -
            done